name: social_media_test
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  path: ^1.8.3
  flutter_svg: ^2.0.9
  http: ^1.2.0
  video_player: ^2.8.3
  provider: ^6.1.2
  
flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: 'assets/images/splash.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: urbanist
      fonts:
        - asset: assets/fonts/urbanist.ttf

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
